# src/report.py
from typing import Dict, List, Tuple

def text_report(vehicle: str, deltas: Dict) -> str:
    lines = [f"AutoDiagTool Report — Vehicle: {vehicle}", ""]
    for k, d in sorted(deltas.items()):
        lines.append(f"{k}: delta {d}")
    return "\n".join(lines)

# -------- PDF generation (ReportLab) --------
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

def _flag_color(flag: str):
    return {
        "GREEN": colors.green,
        "YELLOW": colors.orange,
        "RED": colors.red,
    }.get(flag, colors.black)

def pdf_report(
    pdf_path: str,
    vehicle: str,
    deltas: Dict[str, float],
    flags: Dict[str, str],
    meta: Dict[str, str] | None = None
):
    """
    Create a simple 1-page PDF with header, meta, and a table of deltas+flags.
    """
    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter
    x_margin = 0.75 * inch
    y = height - 1.0 * inch

    # Header
    c.setFont("Helvetica-Bold", 18)
    c.drawString(x_margin, y, "AutoDiagTool — Baseline Comparison")
    y -= 0.35 * inch

    # Vehicle line
    c.setFont("Helvetica", 11)
    c.drawString(x_margin, y, f"Vehicle: {vehicle}")
    y -= 0.25 * inch

    # Optional metadata block
    if meta:
        for k, v in meta.items():
            c.drawString(x_margin, y, f"{k}: {v}")
            y -= 0.2 * inch
        y -= 0.1 * inch

    # Table header
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y, "PID")
    c.drawString(x_margin + 2.0 * inch, y, "Δ vs Baseline")
    c.drawString(x_margin + 4.0 * inch, y, "Flag")
    y -= 0.2 * inch
    c.line(x_margin, y, width - x_margin, y)
    y -= 0.15 * inch
    c.setFont("Helvetica", 11)

    # Rows
    for pid in sorted(deltas.keys()):
        if y < 1.0 * inch:
            c.showPage()
            y = height - 1.0 * inch
            c.setFont("Helvetica-Bold", 12)
            c.drawString(x_margin, y, "PID")
            c.drawString(x_margin + 2.0 * inch, y, "Δ vs Baseline")
            c.drawString(x_margin + 4.0 * inch, y, "Flag")
            y -= 0.2 * inch
            c.line(x_margin, y, width - x_margin, y)
            y -= 0.15 * inch
            c.setFont("Helvetica", 11)

        d = deltas[pid]
        f = flags.get(pid, "")
        c.setFillColor(colors.black)
        c.drawString(x_margin, y, pid)
        c.drawString(x_margin + 2.0 * inch, y, f"{d:+.3f}")
        c.setFillColor(_flag_color(f))
        c.drawString(x_margin + 4.0 * inch, y, f)
        c.setFillColor(colors.black)
        y -= 0.22 * inch

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.grey)
    c.drawRightString(width - x_margin, 0.75 * inch, "Generated by AutoDiagTool MVP")
    c.save()
